### ISSUE TITLE
fabric8 plugin can't find Docker Machine on Windows

### ISSUE THREAD

**Issue by seanf** [fabric8io/shootout-docker-maven#1]
I have Docker Machine set up on Windows 8.1, but I can't get it to work with the fabric8 shootout:

    $ mvn -Pfabric8 clean install -e
    ...
    [ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.15.5:build (start) on project shootout-docker-maven: Execution start of goal io.fabric8:docker-maven-plugin:0.15.5:build failed: No url given, no DOCKER_HOST environment variable and no read/writable '/var/run/docker.sock' -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.15.5:build (start) on project shootout-docker-maven: Execution start of goal io.fabric8:docker-maven-plugin:0.15.5:build failed: No url given, no DOCKER_HOST environment variable and no read/writable '/var/run/docker.sock'
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    Caused by: org.apache.maven.plugin.PluginExecutionException: Execution start of goal io.fabric8:docker-maven-plugin:0.15.5:build failed: No url given, no DOCKER_HOST environment variable and no read/writable '/var/run/docker.sock'
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
    Caused by: java.lang.IllegalArgumentException: No url given, no DOCKER_HOST environment variable and no read/writable '/var/run/docker.sock'
        at io.fabric8.maven.docker.util.EnvUtil.extractUrl(EnvUtil.java:34)
        at io.fabric8.maven.docker.AbstractDockerMojo.createDockerAccess(AbstractDockerMojo.java:227)
        at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:174)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more

I know Docker Machine is working, because I have it working with https://github.com/testcontainers/testcontainers-java-examples

**Comment by rhuss** [comment]
You need to set your `DOCKER_HOST` variable as said in the error message.

When using docker-machine this is best done with

```
eval "$(docker-machine env my-default)"
```

where `my-default` is the name of your docker machine.

Does this help ?

**Comment by seanf** [comment]
Okay, thanks. I assumed the plugin would do this automatically if required, as it was in the other plugin.

Is there some way I can avoid hardcoding a hostname there? "localhost" doesn't seem to work. (I'm more used to Linux docker, so I know nothing about configuring docker machine.)

**Comment by seanf** [comment]
Disregard my last question. This seems to be working:

$ docker-machine start && eval `docker-machine env` && mvn clean install

**Comment by seanf** [comment]
Yep, that passed. I might put in an enhancement request against the plugin for docker-machine integration.

Thanks @rhuss !

**Comment by rhuss** [comment]
There is already a PR pending for direct docker-machine support https://github.com/fabric8io/docker-maven-plugin/pull/437 Feel free to participate in that discussion ;-)

**Comment by seanf** [comment]
Okay, thanks.

**Comment by phxgithub** [comment]
Just to save anyone else some time in hunting down how the implementation of the above PR fix works, see https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/asciidoc/inc/_global-configuration.adoc#docker-machine

**Comment by linzhou-zhong** [comment]
Whatever try to switch on your Docker application firstly. ^^
